<a href="https://colab.research.google.com/github/statje/musthave_mldl_problem_solving_strategy/blob/master/ch5_%EA%B5%90%EC%B0%A8%EA%B2%80%EC%A6%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

k fold 교차 검증

In [1]:
import numpy as np
from sklearn.model_selection import KFold

data = np.array([0,1,2,3,4,5,6,7,8,9])
folds = KFold(n_splits = 5, shuffle = False) # k = 5로 설정 / suffle = False로 데이터를 안섞음.

for train_idx, valid_idx in folds.split(data):
  print(f'훈련 데이터 : {data[train_idx]}, 검증데이터 : {data[valid_idx]}')

훈련 데이터 : [2 3 4 5 6 7 8 9], 검증데이터 : [0 1]
훈련 데이터 : [0 1 4 5 6 7 8 9], 검증데이터 : [2 3]
훈련 데이터 : [0 1 2 3 6 7 8 9], 검증데이터 : [4 5]
훈련 데이터 : [0 1 2 3 4 5 8 9], 검증데이터 : [6 7]
훈련 데이터 : [0 1 2 3 4 5 6 7], 검증데이터 : [8 9]


데이터가 편향되어 있을 수도 있기 때문에 Shuffle 파라미터에 True를 전달함

In [2]:
import numpy as np
from sklearn.model_selection import KFold

data = np.array([0,1,2,3,4,5,6,7,8,9])
folds = KFold(n_splits = 5, shuffle = False) # k = 5로 설정 / suffle = False로 데이터를 안섞음.

for train_idx, valid_idx in folds.split(data):
  print(f'훈련 데이터 : {data[train_idx]}, 검증데이터 : {data[valid_idx]}')

훈련 데이터 : [2 3 4 5 6 7 8 9], 검증데이터 : [0 1]
훈련 데이터 : [0 1 4 5 6 7 8 9], 검증데이터 : [2 3]
훈련 데이터 : [0 1 2 3 6 7 8 9], 검증데이터 : [4 5]
훈련 데이터 : [0 1 2 3 4 5 8 9], 검증데이터 : [6 7]
훈련 데이터 : [0 1 2 3 4 5 6 7], 검증데이터 : [8 9]


층화 K 폴드 교차 검증

In [3]:
#기존 KFold
y = np.array(['스팸']*5 + ['일반']*45)
folds = KFold(n_splits = 5, shuffle = True)

for idx, (train_idx, valid_idx) in enumerate(folds.split(y)):
  print(f'Fold {idx+1} 검증 데이터 타깃값 : ')
  print(y[valid_idx], '\n')

Fold 1 검증 데이터 타깃값 : 
['스팸' '스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 2 검증 데이터 타깃값 : 
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 3 검증 데이터 타깃값 : 
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 4 검증 데이터 타깃값 : 
['일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 5 검증 데이터 타깃값 : 
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 



In [4]:
from sklearn.model_selection import StratifiedKFold

X = np.array(range(50))
y = np.array(['스팸']*5 + ['일반']*45)

folds = StratifiedKFold(n_splits = 5)

for idx, (train_idx, valid_idx) in enumerate(folds.split(X,y)):
  print(f'Fold {idx+1} 검증 데이터 타깃값:')
  print(y[valid_idx], '\n')

Fold 1 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 2 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 3 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 4 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 5 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 



In [5]:
for idx, (train_idx, valid_idx) in enumerate(folds.split(X,y)):
  print(f'Fold {idx+1} 검증 데이터 타깃값:')
  print(valid_idx, '\n')
  print(train_idx, '\n')

Fold 1 검증 데이터 타깃값:
[ 0  5  6  7  8  9 10 11 12 13] 

[ 1  2  3  4 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Fold 2 검증 데이터 타깃값:
[ 1 14 15 16 17 18 19 20 21 22] 

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Fold 3 검증 데이터 타깃값:
[ 2 23 24 25 26 27 28 29 30 31] 

[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Fold 4 검증 데이터 타깃값:
[ 3 32 33 34 35 36 37 38 39 40] 

[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 41 42 43 44 45 46 47 48 49] 

Fold 5 검증 데이터 타깃값:
[ 4 41 42 43 44 45 46 47 48 49] 

[ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40] 

